#!/bin/bash

# Create build-directory
mkdir build

# Move into the build-directory
cd build

# Run CMake to create a Makefile
# Might have to delete files in build first
# cmake.exe -G "MinGW Makefiles" ..
cmake ../

# Make the Makefile using two threads
# mingw32-make.exe -j2
make -j2

# Move the executable to the top-directory
#mv vmc ..
mv .\vmc.exe ..
