#pragma once
#include <memory>
#include <vector>

#include "particle.h"

class Hamiltonian
{
public:
    // Use the default deconstructor generated by the compiler
    virtual ~Hamiltonian() = default;
    /// @brief Compute the local energy of the system.
    /// @param waveFunction The trial wave function to use.
    /// @param particles Vector of particles.
    /// @return The local energy.
    virtual double computeLocalEnergy(
        class WaveFunction &waveFunction,
        std::vector<std::unique_ptr<class Particle>> &particles) = 0;
};
